# coding: utf-8

"""
    Bilddoku

    Part of the server to support Bilddoku client and plugin.   # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: nobody@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.bilddoku_product import BilddokuProduct  # noqa: E501
from swagger_client.rest import ApiException


class TestBilddokuProduct(unittest.TestCase):
    """BilddokuProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBilddokuProduct(self):
        """Test BilddokuProduct"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bilddoku_product.BilddokuProduct()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
