# coding: utf-8

"""
    Bilddoku

    Part of the server to support Bilddoku client and plugin.   # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: nobody@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.points_api import PointsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPointsApi(unittest.TestCase):
    """PointsApi unit test stubs"""

    def setUp(self):
        self.api = PointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_point(self):
        """Test case for get_point

        get point  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
