# coding: utf-8

"""
    Bilddoku

    Part of the server to support Bilddoku client and plugin.   # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: nobody@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bilddoku_product_api import BilddokuProductApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBilddokuProductApi(unittest.TestCase):
    """BilddokuProductApi unit test stubs"""

    def setUp(self):
        self.api = BilddokuProductApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_bilddoku_product(self):
        """Test case for delete_bilddoku_product

        delete Bilddoku produkt  # noqa: E501
        """
        pass

    def test_get_bilddoku_product(self):
        """Test case for get_bilddoku_product

        add new product for a given bilddoku query  # noqa: E501
        """
        pass

    def test_post_bilddoku_product(self):
        """Test case for post_bilddoku_product

        add new product for a given bilddoku query  # noqa: E501
        """
        pass

    def test_put_bilddoku_product(self):
        """Test case for put_bilddoku_product

        add new product for a given bilddoku query  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
