# coding: utf-8

"""
    Bilddoku

    Part of the server to support Bilddoku client and plugin.   # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: nobody@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bilddoku_query_api import BilddokuQueryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBilddokuQueryApi(unittest.TestCase):
    """BilddokuQueryApi unit test stubs"""

    def setUp(self):
        self.api = BilddokuQueryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_bilddoku_query(self):
        """Test case for add_bilddoku_query

        Add a new bilddoku query or update an existing one  # noqa: E501
        """
        pass

    def test_delete_bilddoku_by_point(self):
        """Test case for delete_bilddoku_by_point

        delete Bilddoku for given point  # noqa: E501
        """
        pass

    def test_get_bilddoku_by_point(self):
        """Test case for get_bilddoku_by_point

        get Bilddoku for given point  # noqa: E501
        """
        pass

    def test_get_bilddoku_query_list(self):
        """Test case for get_bilddoku_query_list

        Get next bilddoku_query_id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
