# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Areapp
                                 A QGIS plugin
 Areapp print layout
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-14
        copyright            : (C) 2021 by Camptocamp SA
        email                : info@camptocamp.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import sys
import os.path

sys.path.append(os.path.join(os.path.dirname(__file__), "lib"))


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Areapp class from file Areapp.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .areapp import Areapp

    return Areapp(iface)
