# coding: utf-8

# flake8: noqa
"""
    Bilddoku

    Part of the server to support Bilddoku client and plugin.   # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: nobody@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.bilddoku_product import BilddokuProduct
from swagger_client.models.bilddoku_query import BilddokuQuery
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.type import Type
from swagger_client.models.type_classification import TypeClassification
