# coding: utf-8

"""
    Bilddoku

    Part of the server to support Bilddoku client and plugin.   # noqa: E501

    OpenAPI spec version: 1.0.6
    Contact: nobody@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bilddoku_query_id': 'int'
    }

    attribute_map = {
        'bilddoku_query_id': 'bilddoku_query_id'
    }

    def __init__(self, bilddoku_query_id=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger"""  # noqa: E501
        self._bilddoku_query_id = None
        self.discriminator = None
        if bilddoku_query_id is not None:
            self.bilddoku_query_id = bilddoku_query_id

    @property
    def bilddoku_query_id(self):
        """Gets the bilddoku_query_id of this InlineResponse200.  # noqa: E501


        :return: The bilddoku_query_id of this InlineResponse200.  # noqa: E501
        :rtype: int
        """
        return self._bilddoku_query_id

    @bilddoku_query_id.setter
    def bilddoku_query_id(self, bilddoku_query_id):
        """Sets the bilddoku_query_id of this InlineResponse200.


        :param bilddoku_query_id: The bilddoku_query_id of this InlineResponse200.  # noqa: E501
        :type: int
        """

        self._bilddoku_query_id = bilddoku_query_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
