# coding: utf-8

"""
    Bilddoku

    Part of the server to support Bilddoku client and plugin.   # noqa: E501

    OpenAPI spec version: 1.0.5
    Contact: nobody@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Type(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'identifier': 'int',
        'fr': 'str',
        'de': 'str',
        'it': 'str',
        'en': 'str'
    }

    attribute_map = {
        'identifier': 'identifier',
        'fr': 'fr',
        'de': 'de',
        'it': 'it',
        'en': 'en'
    }

    def __init__(self, identifier=None, fr=None, de=None, it=None, en=None):  # noqa: E501
        """Type - a model defined in Swagger"""  # noqa: E501
        self._identifier = None
        self._fr = None
        self._de = None
        self._it = None
        self._en = None
        self.discriminator = None
        if identifier is not None:
            self.identifier = identifier
        if fr is not None:
            self.fr = fr
        if de is not None:
            self.de = de
        if it is not None:
            self.it = it
        if en is not None:
            self.en = en

    @property
    def identifier(self):
        """Gets the identifier of this Type.  # noqa: E501


        :return: The identifier of this Type.  # noqa: E501
        :rtype: int
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this Type.


        :param identifier: The identifier of this Type.  # noqa: E501
        :type: int
        """

        self._identifier = identifier

    @property
    def fr(self):
        """Gets the fr of this Type.  # noqa: E501


        :return: The fr of this Type.  # noqa: E501
        :rtype: str
        """
        return self._fr

    @fr.setter
    def fr(self, fr):
        """Sets the fr of this Type.


        :param fr: The fr of this Type.  # noqa: E501
        :type: str
        """

        self._fr = fr

    @property
    def de(self):
        """Gets the de of this Type.  # noqa: E501


        :return: The de of this Type.  # noqa: E501
        :rtype: str
        """
        return self._de

    @de.setter
    def de(self, de):
        """Sets the de of this Type.


        :param de: The de of this Type.  # noqa: E501
        :type: str
        """

        self._de = de

    @property
    def it(self):
        """Gets the it of this Type.  # noqa: E501


        :return: The it of this Type.  # noqa: E501
        :rtype: str
        """
        return self._it

    @it.setter
    def it(self, it):
        """Sets the it of this Type.


        :param it: The it of this Type.  # noqa: E501
        :type: str
        """

        self._it = it

    @property
    def en(self):
        """Gets the en of this Type.  # noqa: E501


        :return: The en of this Type.  # noqa: E501
        :rtype: str
        """
        return self._en

    @en.setter
    def en(self, en):
        """Sets the en of this Type.


        :param en: The en of this Type.  # noqa: E501
        :type: str
        """

        self._en = en

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Type, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Type):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
